1. ruleaza corect 
~2s

2. SSHException(paramiko.ssh_exception.SSHException: encountered RSA key, expected OPENSSH key) 
~31s

ERROR - Error executing command: encountered RSA key, expected OPENSSH key
Traceback (most recent call last):
  File "/app/manager/instancemanager.py", line 164, in run_command
    ssh.connect(
  File "/usr/local/lib/python3.12/site-packages/paramiko/client.py", line 485, in connect
    self._auth(
  File "/usr/local/lib/python3.12/site-packages/paramiko/client.py", line 818, in _auth
    raise saved_exception
  File "/usr/local/lib/python3.12/site-packages/paramiko/client.py", line 730, in _auth
    key = self._key_from_filepath(
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paramiko/client.py", line 638, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paramiko/pkey.py", line 421, in from_private_key_file
    key = cls(filename=filename, password=password)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paramiko/ed25519key.py", line 60, in __init__
    pkformat, data = self._read_private_key("OPENSSH", f)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paramiko/pkey.py", line 529, in _read_private_key
    raise SSHException(
paramiko.ssh_exception.SSHException: encountered RSA key, expected OPENSSH key

3. EOFError()
~2s

 ERROR - Error executing command: 
Traceback (most recent call last):
  File "/app/manager/instancemanager.py", line 184, in run_command
    stdin, stdout, stderr = ssh.exec_command(command)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paramiko/client.py", line 560, in exec_command
    chan = self._transport.open_session(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paramiko/transport.py", line 959, in open_session
    return self.open_channel(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paramiko/transport.py", line 1090, in open_channel
    raise e
  File "/usr/local/lib/python3.12/site-packages/paramiko/transport.py", line 2159, in run
    ptype, m = self.packetizer.read_message()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paramiko/packet.py", line 463, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paramiko/packet.py", line 310, in read_all
    raise EOFError()
EOFError


4. ed25519key
~47s
2:46

 Traceback (most recent call last):
  File "/app/manager/instancemanager.py", line 169, in run_command
    stdin, stdout, stderr = ssh.exec_command(command)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paramiko/client.py", line 566, in exec_command
    chan.exec_command(command)
  File "/usr/local/lib/python3.12/site-packages/paramiko/channel.py", line 70, in _check
    return func(self, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paramiko/channel.py", line 255, in exec_command
    self._wait_for_event()
  File "/usr/local/lib/python3.12/site-packages/paramiko/channel.py", line 1224, in _wait_for_event
    raise e
  File "/usr/local/lib/python3.12/site-packages/paramiko/transport.py", line 2159, in run
    ptype, m = self.packetizer.read_message()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paramiko/packet.py", line 463, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paramiko/packet.py", line 310, in read_all
    raise EOFError()
EOFError